/**
 * Node Graph to Iris GLSL Code Generator
 * Compiles visual nodes and connections into valid, optimized, beautifully commented GLSL code.
 */

import { ShaderNode, NodeConnection, PortDataType } from '../types/shader';

export function generateGlslFromNodes(
  nodes: ShaderNode[],
  connections: NodeConnection[],
  options: {
    passName?: string; // 'gbuffers_terrain' | 'composite' | 'final'
  } = {}
): string {
  const masterNode = nodes.find(n => n.category === 'output' || n.id === 'master_output');

  // Topological sorting of nodes from inputs to outputs
  const executionOrder = getTopologicalOrder(nodes, connections);

  // Collect needed helper functions
  const neededHelpers = new Set<string>();
  executionOrder.forEach(node => {
    const lower = node.name.toLowerCase();
    if (lower.includes('water')) neededHelpers.add('waterWave');
    if (lower.includes('noise') || node.category === 'procedural') neededHelpers.add('noise');
    if (lower.includes('aces') || lower.includes('tone')) neededHelpers.add('acesTone');
    if (lower.includes('waving')) neededHelpers.add('windWave');
  });

  let code = `/* ====================================================================
 * Minecraft 1.21+ Iris Shader Studio
 * Auto-generated by Visual Node Scripting Engine
 * Compatible with Iris Shader Mod (Fabric / Quilt / NeoForge)
 * ==================================================================== */

#version 330 compatibility

/* ---------- Iris Built-in Uniforms ---------- */
uniform mat4 gbufferModelView;
uniform mat4 gbufferProjection;
uniform mat4 gbufferModelViewInverse;
uniform mat4 gbufferProjectionInverse;

uniform vec3 cameraPosition;
uniform int worldTime;
uniform float frameTimeCounter;
uniform float rainStrength;
uniform vec3 sunPosition;
uniform vec3 upPosition;

uniform sampler2D colortex0; // Albedo texture
uniform sampler2D depthtex0; // Depth buffer
uniform sampler2D colortex1; // Normal / Lightmap

/* ---------- Interpolated Inputs from Vertex Shader ---------- */
varying vec2 texcoord;
varying vec4 glColor;
varying vec3 normal;
varying vec3 worldPosition;

`;

  // Insert helper GLSL functions if required
  if (neededHelpers.has('noise')) {
    code += `// Fast Procedural Noise for Minecraft Textures
float hash(vec2 p) {
    p = 50.0 * fract(p * 0.3183099 + vec2(0.71, 0.113));
    return -1.0 + 2.0 * fract(16.0 * fract(p.x * p.y * (p.x + p.y)));
}

float noise2D(vec2 p) {
    vec2 i = floor(p);
    vec2 f = fract(p);
    vec2 u = f * f * (3.0 - 2.0 * f);
    return mix(mix(hash(i + vec2(0.0,0.0)), hash(i + vec2(1.0,0.0)), u.x),
               mix(hash(i + vec2(0.0,1.0)), hash(i + vec2(1.0,1.0)), u.x), u.y);
}

`;
  }

  if (neededHelpers.has('acesTone')) {
    code += `// ACES Cinematic Tone Mapping (Iris Standard)
vec3 acesFilm(vec3 x) {
    float a = 2.51;
    float b = 0.03;
    float c = 2.43;
    float d = 0.59;
    float e = 0.14;
    return clamp((x * (a * x + b)) / (x * (c * x + d) + e), 0.0, 1.0);
}

`;
  }

  if (neededHelpers.has('windWave')) {
    code += `// Minecraft Wind Sway Math for Leaves & Grass
vec3 calculateWindSway(vec3 pos, float time, float speed, float strength) {
    float wave = sin(pos.x * 2.0 + time * speed) * cos(pos.z * 1.5 + time * (speed * 0.8));
    return vec3(wave * strength * 0.1, sin(time * speed * 1.5) * strength * 0.04, wave * strength * 0.1);
}

`;
  }

  code += `void main() {
    // Read original Minecraft block albedo texture
    vec4 baseAlbedo = texture2D(colortex0, texcoord) * glColor;
    if (baseAlbedo.a < 0.1) {
        discard;
    }

    vec3 viewNormal = normalize(normal);
    vec3 lightDir = normalize(sunPosition);
    float NdotL = max(dot(viewNormal, lightDir), 0.0);
    float dayCycle = clamp(cos(float(worldTime) * 0.000261799), 0.0, 1.0);

    /* ---------- Visual Scripting Node Computations ---------- */
`;

  // Mappings to track variable names and strongly-typed data types
  const varMap = new Map<string, string>(); // `${nodeId}_${portId}` -> variable name
  const typeMap = new Map<string, PortDataType>(); // variable name -> type

  // Register baseline variables
  typeMap.set('baseAlbedo.rgb', 'vec3');
  typeMap.set('baseAlbedo.a', 'float');
  typeMap.set('baseAlbedo', 'vec4');
  typeMap.set('viewNormal', 'vec3');
  typeMap.set('lightDir', 'vec3');
  typeMap.set('texcoord', 'vec2');
  typeMap.set('worldPosition', 'vec3');

  executionOrder.forEach((node, idx) => {
    const nodeVar = `node_${idx}_${sanitizeName(node.name)}`;

    // Helper to get connected input value or port defaultValue with its detected type
    const getInputInfo = (portId: string, fallbackLiteral: string, fallbackType: PortDataType = 'vec3'): { val: string; type: PortDataType } => {
      const conn = connections.find(c => c.toNodeId === node.id && c.toPortId === portId);
      if (conn) {
        const fromVar = varMap.get(`${conn.fromNodeId}_${conn.fromPortId}`);
        if (fromVar) {
          const t = typeMap.get(fromVar) || fallbackType;
          return { val: fromVar, type: t };
        }
      }
      const port = node.inputs.find(p => p.id === portId);
      if (port && port.value !== undefined) {
        return { val: formatLiteral(port.value, port.type), type: port.type };
      }
      return { val: fallbackLiteral, type: fallbackType };
    };

    code += `\n    // Node: ${node.name} (${node.category})\n`;

    switch (node.category) {
      case 'input': {
        const lower = node.name.toLowerCase();
        if (node.id.includes('time') || lower.includes('time')) {
          code += `    float ${nodeVar} = frameTimeCounter;\n`;
          typeMap.set(nodeVar, 'float');
          varMap.set(`${node.id}_time`, nodeVar);
          varMap.set(`${node.id}_out`, nodeVar);
        } else if (lower.includes('sun')) {
          code += `    vec3 ${nodeVar} = lightDir;\n`;
          typeMap.set(nodeVar, 'vec3');
          varMap.set(`${node.id}_sunDir`, nodeVar);
          varMap.set(`${node.id}_out`, nodeVar);
        } else if (lower.includes('rain')) {
          code += `    float ${nodeVar} = rainStrength;\n`;
          typeMap.set(nodeVar, 'float');
          varMap.set(`${node.id}_rain`, nodeVar);
          varMap.set(`${node.id}_out`, nodeVar);
        } else if (lower.includes('uv')) {
          code += `    vec2 ${nodeVar} = texcoord;\n`;
          typeMap.set(nodeVar, 'vec2');
          varMap.set(`${node.id}_uv`, nodeVar);
          varMap.set(`${node.id}_out`, nodeVar);
        } else if (lower.includes('albedo') || lower.includes('base')) {
          code += `    vec4 ${nodeVar} = baseAlbedo;\n`;
          typeMap.set(nodeVar, 'vec4');
          typeMap.set(`${nodeVar}.rgb`, 'vec3');
          typeMap.set(`${nodeVar}.a`, 'float');
          varMap.set(`${node.id}_color`, nodeVar);
          varMap.set(`${node.id}_rgb`, `${nodeVar}.rgb`);
          varMap.set(`${node.id}_alpha`, `${nodeVar}.a`);
          varMap.set(`${node.id}_out`, `${nodeVar}.rgb`);
        } else {
          code += `    vec3 ${nodeVar} = viewNormal;\n`;
          typeMap.set(nodeVar, 'vec3');
          varMap.set(`${node.id}_normal`, nodeVar);
          varMap.set(`${node.id}_out`, nodeVar);
        }
        break;
      }

      case 'color': {
        const lower = node.name.toLowerCase();
        if (lower.includes('constant') || lower.includes('picker')) {
          const hex = node.data?.hex || '#ffb74d';
          const rgb = hexToGlslVec3(hex);
          code += `    vec3 ${nodeVar} = ${rgb};\n`;
          typeMap.set(nodeVar, 'vec3');
          varMap.set(`${node.id}_color`, nodeVar);
          varMap.set(`${node.id}_out`, nodeVar);
        } else if (lower.includes('cel') || lower.includes('toon')) {
          const inInfo = getInputInfo('inColor', 'baseAlbedo.rgb', 'vec3');
          const steps = node.data?.steps || 3;
          code += `    float ${nodeVar}_diffuse = floor(NdotL * ${steps}.0 + 0.5) / ${steps}.0;\n`;
          code += `    vec3 ${nodeVar} = ${inInfo.val} * (${nodeVar}_diffuse * 0.75 + 0.25);\n`;
          typeMap.set(nodeVar, 'vec3');
          varMap.set(`${node.id}_out`, nodeVar);
          varMap.set(`${node.id}_diffuse`, `${nodeVar}_diffuse`);
        } else if (lower.includes('tone') || lower.includes('aces')) {
          const inInfo = getInputInfo('inColor', 'baseAlbedo.rgb', 'vec3');
          const exposure = node.data?.exposure || 1.2;
          code += `    vec3 ${nodeVar} = acesFilm(${inInfo.val} * ${exposure.toFixed(2)});\n`;
          typeMap.set(nodeVar, 'vec3');
          varMap.set(`${node.id}_out`, nodeVar);
        } else if (lower.includes('ambient')) {
          const inInfo = getInputInfo('inColor', 'baseAlbedo.rgb', 'vec3');
          const strength = node.data?.strength || 0.4;
          code += `    vec3 ${nodeVar} = ${inInfo.val} + vec3(0.08, 0.11, 0.16) * ${strength.toFixed(2)};\n`;
          typeMap.set(nodeVar, 'vec3');
          varMap.set(`${node.id}_out`, nodeVar);
        } else {
          const inInfo = getInputInfo('inColor', 'baseAlbedo.rgb', 'vec3');
          code += `    vec3 ${nodeVar} = ${inInfo.val};\n`;
          typeMap.set(nodeVar, 'vec3');
          varMap.set(`${node.id}_out`, nodeVar);
        }
        break;
      }

      case 'effects': {
        const lower = node.name.toLowerCase();
        if (lower.includes('waving')) {
          const speed = node.data?.speed || 2.5;
          const strength = node.data?.strength || 0.15;
          code += `    vec3 ${nodeVar}_wave = calculateWindSway(worldPosition, frameTimeCounter, ${speed.toFixed(2)}, ${strength.toFixed(2)});\n`;
          code += `    vec3 ${nodeVar} = ${nodeVar}_wave;\n`;
          typeMap.set(nodeVar, 'vec3');
          varMap.set(`${node.id}_offset`, `${nodeVar}_wave`);
          varMap.set(`${node.id}_out`, `${nodeVar}_wave`);
        } else if (lower.includes('water')) {
          const waveSpeed = node.data?.speed || 1.8;
          code += `    float ${nodeVar}_caustic = sin(texcoord.x * 24.0 + frameTimeCounter * ${waveSpeed.toFixed(2)}) * cos(texcoord.y * 24.0 + frameTimeCounter * ${(waveSpeed * 0.9).toFixed(2)}) * 0.5 + 0.5;\n`;
          code += `    vec3 ${nodeVar}_tint = vec3(0.12, 0.45, 0.78) + vec3(0.2, 0.35, 0.4) * ${nodeVar}_caustic * 0.4;\n`;
          code += `    vec3 ${nodeVar} = ${nodeVar}_tint;\n`;
          typeMap.set(nodeVar, 'vec3');
          typeMap.set(`${nodeVar}_caustic`, 'float');
          varMap.set(`${node.id}_color`, `${nodeVar}_tint`);
          varMap.set(`${node.id}_caustic`, `${nodeVar}_caustic`);
          varMap.set(`${node.id}_out`, `${nodeVar}_tint`);
        } else if (lower.includes('fog')) {
          const density = node.data?.density || 0.015;
          const fogColor = node.data?.fogColor ? hexToGlslVec3(node.data.fogColor) : 'vec3(0.68, 0.78, 0.88)';
          const inInfo = getInputInfo('inColor', 'baseAlbedo.rgb', 'vec3');
          code += `    float ${nodeVar}_dist = length(worldPosition);\n`;
          code += `    float ${nodeVar}_factor = clamp(exp(-${nodeVar}_dist * ${density.toFixed(4)}), 0.0, 1.0);\n`;
          code += `    vec3 ${nodeVar} = mix(${fogColor}, ${inInfo.val}, ${nodeVar}_factor);\n`;
          typeMap.set(nodeVar, 'vec3');
          varMap.set(`${node.id}_out`, nodeVar);
          varMap.set(`${node.id}_fogFactor`, `${nodeVar}_factor`);
        } else if (lower.includes('vignette')) {
          const inInfo = getInputInfo('inColor', 'baseAlbedo.rgb', 'vec3');
          const intensity = node.data?.intensity || 0.4;
          code += `    vec2 ${nodeVar}_uv = texcoord * (1.0 - texcoord.yx);\n`;
          code += `    float ${nodeVar}_vig = clamp(${nodeVar}_uv.x * ${nodeVar}_uv.y * 15.0, 0.0, 1.0);\n`;
          code += `    float ${nodeVar}_amount = clamp(pow(${nodeVar}_vig, ${intensity.toFixed(2)}), 0.0, 1.0);\n`;
          code += `    vec3 ${nodeVar} = ${inInfo.val} * ${nodeVar}_amount;\n`;
          typeMap.set(nodeVar, 'vec3');
          varMap.set(`${node.id}_out`, nodeVar);
        } else if (lower.includes('bloom') || lower.includes('glow')) {
          const inInfo = getInputInfo('inColor', 'baseAlbedo.rgb', 'vec3');
          const threshold = node.data?.threshold || 0.8;
          code += `    float ${nodeVar}_lum = dot(${inInfo.val}, vec3(0.2126, 0.7152, 0.0722));\n`;
          code += `    vec3 ${nodeVar}_bloom = max(${inInfo.val} - vec3(${threshold.toFixed(2)}), vec3(0.0)) * 2.0;\n`;
          code += `    vec3 ${nodeVar} = ${inInfo.val} + ${nodeVar}_bloom;\n`;
          typeMap.set(nodeVar, 'vec3');
          varMap.set(`${node.id}_out`, nodeVar);
          varMap.set(`${node.id}_bloom`, `${nodeVar}_bloom`);
        } else if (lower.includes('pixelate')) {
          const resolution = node.data?.resolution || 128.0;
          code += `    vec2 ${nodeVar}_pixUv = floor(texcoord * ${resolution.toFixed(1)}) / ${resolution.toFixed(1)};\n`;
          code += `    vec4 ${nodeVar} = texture2D(colortex0, ${nodeVar}_pixUv) * glColor;\n`;
          typeMap.set(nodeVar, 'vec4');
          typeMap.set(`${nodeVar}.rgb`, 'vec3');
          varMap.set(`${node.id}_out`, `${nodeVar}.rgb`);
          varMap.set(`${node.id}_uv`, `${nodeVar}_pixUv`);
        } else {
          const inInfo = getInputInfo('inColor', 'baseAlbedo.rgb', 'vec3');
          code += `    vec3 ${nodeVar} = ${inInfo.val};\n`;
          typeMap.set(nodeVar, 'vec3');
          varMap.set(`${node.id}_out`, nodeVar);
        }
        break;
      }

      case 'math': {
        const infoA = getInputInfo('a', '1.0', 'vec3');
        const infoB = getInputInfo('b', '1.0', 'vec3');
        const lower = node.name.toLowerCase();

        if (lower.includes('number') || lower.includes('slider')) {
          const val = node.data?.value !== undefined ? Number(node.data.value) : 1.0;
          code += `    float ${nodeVar} = ${val.toFixed(3)};\n`;
          typeMap.set(nodeVar, 'float');
          varMap.set(`${node.id}_val`, nodeVar);
          varMap.set(`${node.id}_out`, nodeVar);
          return;
        }

        // Determine math output type based on operands
        let outType: PortDataType = 'vec3';
        if (infoA.type === 'float' && infoB.type === 'float') {
          outType = 'float';
        } else if (infoA.type === 'vec4' || infoB.type === 'vec4') {
          outType = 'vec4';
        } else if (infoA.type === 'vec2' || infoB.type === 'vec2') {
          outType = 'vec2';
        } else {
          outType = 'vec3';
        }

        // Type-safe operand formatting for GLSL
        let opA = infoA.val;
        let opB = infoB.val;

        if (lower.includes('multiply')) {
          // In GLSL: vec3 * float is valid; float * vec3 is valid; vec3 * vec3 is component-wise
          code += `    ${outType} ${nodeVar} = ${opA} * ${opB};\n`;
        } else if (lower.includes('add')) {
          // In GLSL: adding float to vec3 requires vec3(float)
          if (outType === 'vec3' && infoA.type === 'float') opA = `vec3(${opA})`;
          if (outType === 'vec3' && infoB.type === 'float') opB = `vec3(${opB})`;
          code += `    ${outType} ${nodeVar} = ${opA} + ${opB};\n`;
        } else if (lower.includes('mix') || lower.includes('lerp')) {
          const infoFactor = getInputInfo('factor', '0.5', 'float');
          code += `    ${outType} ${nodeVar} = mix(${opA}, ${opB}, ${infoFactor.val});\n`;
        } else if (lower.includes('sine') || lower.includes('sin')) {
          code += `    ${infoA.type} ${nodeVar} = sin(${opA});\n`;
          outType = infoA.type;
        } else if (lower.includes('clamp')) {
          const minInfo = getInputInfo('min', '0.0', 'float');
          const maxInfo = getInputInfo('max', '1.0', 'float');
          code += `    ${infoA.type} ${nodeVar} = clamp(${opA}, ${minInfo.val}, ${maxInfo.val});\n`;
          outType = infoA.type;
        } else {
          code += `    ${outType} ${nodeVar} = ${opA} * ${opB};\n`;
        }

        typeMap.set(nodeVar, outType);
        varMap.set(`${node.id}_out`, nodeVar);
        break;
      }

      case 'custom': {
        const expr = node.customCode || '(inA * inB + inC)';
        const inA = getInputInfo('inA', '1.0', 'vec3').val;
        const inB = getInputInfo('inB', '1.0', 'vec3').val;
        const inC = getInputInfo('inC', '0.0', 'float').val;
        const replacedExpr = expr
          .replace(/\binA\b/g, inA)
          .replace(/\binB\b/g, inB)
          .replace(/\binC\b/g, inC);
        code += `    vec3 ${nodeVar} = vec3(${replacedExpr});\n`;
        typeMap.set(nodeVar, 'vec3');
        varMap.set(`${node.id}_out`, nodeVar);
        break;
      }

      case 'output': {
        const inColor = getInputInfo('color', 'baseAlbedo.rgb', 'vec3').val;
        const inAlpha = getInputInfo('alpha', 'baseAlbedo.a', 'float').val;
        code += `    // Master Output mapping to gl_FragColor / colortex0\n`;
        code += `    vec3 finalRgb = ${inColor};\n`;
        code += `    float finalAlpha = ${inAlpha};\n`;
        code += `    gl_FragColor = vec4(finalRgb, finalAlpha);\n`;
        break;
      }
    }
  });

  // If no explicit master output node was processed
  if (!masterNode) {
    const lastNode = executionOrder[executionOrder.length - 1];
    const lastVar = lastNode ? varMap.get(`${lastNode.id}_out`) : 'baseAlbedo.rgb';
    code += `\n    // Fallback Final Color Assignment\n`;
    code += `    gl_FragColor = vec4(${lastVar || 'baseAlbedo.rgb'}, baseAlbedo.a);\n`;
  }

  code += `}\n`;
  return code;
}

function sanitizeName(name: string): string {
  return name.replace(/[^a-zA-Z0-9]/g, '_').toLowerCase();
}

function formatLiteral(value: any, type: string): string {
  if (typeof value === 'number') {
    return Number.isInteger(value) ? `${value}.0` : `${value}`;
  }
  if (type === 'vec3' && Array.isArray(value)) {
    return `vec3(${value.map(v => Number(v).toFixed(2)).join(', ')})`;
  }
  return String(value);
}

function hexToGlslVec3(hex: string): string {
  const clean = hex.replace('#', '');
  if (clean.length === 6) {
    const r = (parseInt(clean.slice(0, 2), 16) / 255).toFixed(3);
    const g = (parseInt(clean.slice(2, 4), 16) / 255).toFixed(3);
    const b = (parseInt(clean.slice(4, 6), 16) / 255).toFixed(3);
    return `vec3(${r}, ${g}, ${b})`;
  }
  return 'vec3(1.0, 1.0, 1.0)';
}

/**
 * Topologically sorts the nodes so inputs are declared before dependents
 */
function getTopologicalOrder(nodes: ShaderNode[], connections: NodeConnection[]): ShaderNode[] {
  const order: ShaderNode[] = [];
  const visited = new Set<string>();
  const visiting = new Set<string>();

  const nodeMap = new Map(nodes.map(n => [n.id, n]));

  function dfs(nodeId: string) {
    if (visited.has(nodeId)) return;
    if (visiting.has(nodeId)) return; // prevent circular recursion
    visiting.add(nodeId);

    // Find nodes that feed into this node
    const incomingConns = connections.filter(c => c.toNodeId === nodeId);
    for (const conn of incomingConns) {
      if (nodeMap.has(conn.fromNodeId)) {
        dfs(conn.fromNodeId);
      }
    }

    visiting.delete(nodeId);
    visited.add(nodeId);
    const node = nodeMap.get(nodeId);
    if (node) order.push(node);
  }

  // Start DFS from output nodes or from all nodes
  nodes.forEach(node => {
    if (!visited.has(node.id)) {
      dfs(node.id);
    }
  });

  return order;
}
