/**
 * Iris Shader Preset Templates
 * Complete starter templates ready for beginners with node setups and customized settings.
 */

import { PresetTemplate } from '../types/shader';

export const SHADER_PRESETS: PresetTemplate[] = [
  {
    id: 'fantasy_golden',
    title: 'Fantasy Golden Hour',
    subtitle: 'Warm sunlight, ACES cinematic tone, and swaying foliage',
    badge: 'Popular',
    previewColor: '#f59e0b',
    description: 'Brings warm magical sunset lighting, filmic tone mapping, and gentle wind breeze to Minecraft trees and grass.',
    metadata: {
      name: 'Fantasy_Golden_Hour',
      author: 'ShaderCraft Studio',
      version: '1.0.0',
      description: 'Cinematic golden hour and waving leaves for Minecraft 1.21+ Iris',
      enableWavingLeaves: true,
      enableDynamicWater: true,
      enableGodRays: true,
      enableBloom: true,
      saturationBoost: 1.25,
    },
    nodes: [
      {
        id: 'n_albedo',
        name: 'Block Albedo',
        category: 'input',
        description: 'Original Minecraft block texture and color tint',
        x: 60,
        y: 120,
        inputs: [],
        outputs: [
          { id: 'color', name: 'Color (RGBA)', type: 'vec4' },
          { id: 'rgb', name: 'RGB', type: 'vec3' },
        ],
      },
      {
        id: 'n_sun_tint',
        name: 'Sunlight Tint',
        category: 'color',
        description: 'Warm golden sunlight color',
        x: 60,
        y: 320,
        inputs: [],
        outputs: [{ id: 'color', name: 'RGB', type: 'vec3' }],
        data: { hex: '#ffca7a' },
      },
      {
        id: 'n_waving',
        name: 'Waving Foliage',
        category: 'effects',
        description: 'Calculates wind sway offset for leaves, grass, and crops',
        x: 60,
        y: 500,
        inputs: [],
        outputs: [{ id: 'offset', name: 'Wave Offset', type: 'vec3' }],
        data: { speed: 2.2, strength: 0.18 },
      },
      {
        id: 'n_mult_light',
        name: 'Apply Sunlight',
        category: 'math',
        description: 'Multiplies block color by warm sunlight',
        x: 340,
        y: 160,
        inputs: [
          { id: 'a', name: 'Color', type: 'vec3' },
          { id: 'b', name: 'Sunlight', type: 'vec3' },
        ],
        outputs: [{ id: 'out', name: 'Result', type: 'vec3' }],
      },
      {
        id: 'n_aces',
        name: 'ACES Tone Map',
        category: 'color',
        description: 'Cinematic dynamic range tone mapping curve',
        x: 600,
        y: 160,
        inputs: [{ id: 'inColor', name: 'HDR Color', type: 'vec3' }],
        outputs: [{ id: 'out', name: 'LDR Color', type: 'vec3' }],
        data: { exposure: 1.2 },
      },
      {
        id: 'n_vignette',
        name: 'Camera Vignette',
        category: 'effects',
        description: 'Soft cinematic darkening around viewport edges',
        x: 860,
        y: 160,
        inputs: [{ id: 'inColor', name: 'Color', type: 'vec3' }],
        outputs: [{ id: 'out', name: 'Color', type: 'vec3' }],
        data: { intensity: 0.35 },
      },
      {
        id: 'master_output',
        name: 'Iris Master Output',
        category: 'output',
        description: 'Final frame output sent to Minecraft screen',
        x: 1140,
        y: 200,
        inputs: [
          { id: 'color', name: 'Final Color', type: 'vec3' },
          { id: 'alpha', name: 'Alpha', type: 'float', defaultValue: 1.0 },
        ],
        outputs: [],
      },
    ],
    connections: [
      { id: 'c1', fromNodeId: 'n_albedo', fromPortId: 'rgb', toNodeId: 'n_mult_light', toPortId: 'a' },
      { id: 'c2', fromNodeId: 'n_sun_tint', fromPortId: 'color', toNodeId: 'n_mult_light', toPortId: 'b' },
      { id: 'c3', fromNodeId: 'n_mult_light', fromPortId: 'out', toNodeId: 'n_aces', toPortId: 'inColor' },
      { id: 'c4', fromNodeId: 'n_aces', fromPortId: 'out', toNodeId: 'n_vignette', toPortId: 'inColor' },
      { id: 'c5', fromNodeId: 'n_vignette', fromPortId: 'out', toNodeId: 'master_output', toPortId: 'color' },
    ],
  },
  {
    id: 'ghibli_anime',
    title: 'Ghibli Cel-Shaded Anime',
    subtitle: 'Stepped toon lighting, vibrant grass, and stylized outlines',
    badge: 'Stylized',
    previewColor: '#10b981',
    description: 'Transform Minecraft into a lush anime landscape inspired by Studio Ghibli films with bold stepped shadows.',
    metadata: {
      name: 'Ghibli_Anime_Style',
      author: 'ShaderCraft Studio',
      version: '1.0.0',
      description: 'Anime style cel-shaded toon lighting for Minecraft Iris',
      enableWavingLeaves: true,
      enableDynamicWater: true,
      enableGodRays: false,
      enableBloom: true,
      saturationBoost: 1.4,
    },
    nodes: [
      {
        id: 'n_albedo',
        name: 'Block Albedo',
        category: 'input',
        description: 'Base Minecraft texture',
        x: 60,
        y: 140,
        inputs: [],
        outputs: [{ id: 'rgb', name: 'RGB', type: 'vec3' }],
      },
      {
        id: 'n_cel',
        name: 'Toon Cel-Shading',
        category: 'color',
        description: 'Quantizes lighting into discrete anime color bands',
        x: 340,
        y: 140,
        inputs: [{ id: 'inColor', name: 'Base Color', type: 'vec3' }],
        outputs: [{ id: 'out', name: 'Toon Shaded', type: 'vec3' }],
        data: { steps: 3 },
      },
      {
        id: 'n_sky_ambient',
        name: 'Anime Ambient Sky',
        category: 'color',
        description: 'Adds clean cyan-blue skylight bounce',
        x: 620,
        y: 140,
        inputs: [{ id: 'inColor', name: 'Color', type: 'vec3' }],
        outputs: [{ id: 'out', name: 'Result', type: 'vec3' }],
        data: { strength: 0.5 },
      },
      {
        id: 'n_bloom',
        name: 'Soft Glow Bloom',
        category: 'effects',
        description: 'Adds radiant glow to bright surfaces and flowers',
        x: 880,
        y: 140,
        inputs: [{ id: 'inColor', name: 'Color', type: 'vec3' }],
        outputs: [{ id: 'out', name: 'Color', type: 'vec3' }],
        data: { threshold: 0.75 },
      },
      {
        id: 'master_output',
        name: 'Iris Master Output',
        category: 'output',
        description: 'Render to Minecraft screen',
        x: 1140,
        y: 180,
        inputs: [{ id: 'color', name: 'Final Color', type: 'vec3' }],
        outputs: [],
      },
    ],
    connections: [
      { id: 'c1', fromNodeId: 'n_albedo', fromPortId: 'rgb', toNodeId: 'n_cel', toPortId: 'inColor' },
      { id: 'c2', fromNodeId: 'n_cel', fromPortId: 'out', toNodeId: 'n_sky_ambient', toPortId: 'inColor' },
      { id: 'c3', fromNodeId: 'n_sky_ambient', fromPortId: 'out', toNodeId: 'n_bloom', toPortId: 'inColor' },
      { id: 'c4', fromNodeId: 'n_bloom', fromPortId: 'out', toNodeId: 'master_output', toPortId: 'color' },
    ],
  },
  {
    id: 'crystal_water',
    title: 'Crystal Clear Water & Caustics',
    subtitle: 'Dual-frequency water caustics, wave distortion, and aquatic tint',
    badge: 'Water Focus',
    previewColor: '#06b6d4',
    description: 'Crystal turquoise oceans with animated wave caustics and sparkling specular highlights.',
    metadata: {
      name: 'Crystal_Clear_Water',
      author: 'ShaderCraft Studio',
      version: '1.0.0',
      description: 'Lush tropical water caustics for Minecraft 1.21+ Iris',
      enableWavingLeaves: false,
      enableDynamicWater: true,
      enableGodRays: true,
      enableBloom: false,
      saturationBoost: 1.15,
    },
    nodes: [
      {
        id: 'n_albedo',
        name: 'Block Albedo',
        category: 'input',
        description: 'Underwater blocks and terrain',
        x: 60,
        y: 120,
        inputs: [],
        outputs: [{ id: 'rgb', name: 'RGB', type: 'vec3' }],
      },
      {
        id: 'n_water_fx',
        name: 'Water Waves & Caustic',
        category: 'effects',
        description: 'Simulates underwater light refraction patterns',
        x: 340,
        y: 120,
        inputs: [],
        outputs: [
          { id: 'color', name: 'Water Tint', type: 'vec3' },
          { id: 'caustic', name: 'Caustic Intensity', type: 'float' },
        ],
        data: { speed: 2.0 },
      },
      {
        id: 'n_mix_water',
        name: 'Water Blending',
        category: 'math',
        description: 'Blends seabed terrain with crystal water surface',
        x: 640,
        y: 140,
        inputs: [
          { id: 'a', name: 'Terrain RGB', type: 'vec3' },
          { id: 'b', name: 'Water Surface', type: 'vec3' },
          { id: 'factor', name: 'Blend Alpha', type: 'float', defaultValue: 0.65 },
        ],
        outputs: [{ id: 'out', name: 'Result', type: 'vec3' }],
      },
      {
        id: 'master_output',
        name: 'Iris Master Output',
        category: 'output',
        description: 'Final render',
        x: 960,
        y: 160,
        inputs: [{ id: 'color', name: 'Final Color', type: 'vec3' }],
        outputs: [],
      },
    ],
    connections: [
      { id: 'c1', fromNodeId: 'n_albedo', fromPortId: 'rgb', toNodeId: 'n_mix_water', toPortId: 'a' },
      { id: 'c2', fromNodeId: 'n_water_fx', fromPortId: 'color', toNodeId: 'n_mix_water', toPortId: 'b' },
      { id: 'c3', fromNodeId: 'n_mix_water', fromPortId: 'out', toNodeId: 'master_output', toPortId: 'color' },
    ],
  },
  {
    id: 'midnight_aurora',
    title: 'Midnight Aurora & Glowing Ores',
    subtitle: 'Deep indigo nights, bright glowing torches, and atmospheric fog',
    badge: 'Night Style',
    previewColor: '#8b5cf6',
    description: 'Transforms nighttime into an ethereal dreamscape where torches, redstone, and diamond ores glow radiantly.',
    metadata: {
      name: 'Midnight_Aurora',
      author: 'ShaderCraft Studio',
      version: '1.0.0',
      description: 'Atmospheric dark night with neon ore emission for Minecraft Iris',
      enableWavingLeaves: true,
      enableDynamicWater: true,
      enableGodRays: false,
      enableBloom: true,
      saturationBoost: 1.3,
    },
    nodes: [
      {
        id: 'n_albedo',
        name: 'Block Albedo',
        category: 'input',
        description: 'Base texture',
        x: 60,
        y: 140,
        inputs: [],
        outputs: [{ id: 'rgb', name: 'RGB', type: 'vec3' }],
      },
      {
        id: 'n_night_tint',
        name: 'Indigo Night Tint',
        category: 'color',
        description: 'Dark moody midnight tint',
        x: 60,
        y: 340,
        inputs: [],
        outputs: [{ id: 'color', name: 'Color', type: 'vec3' }],
        data: { hex: '#1e1b4b' },
      },
      {
        id: 'n_mix_night',
        name: 'Night Lighting',
        category: 'math',
        description: 'Applies midnight atmosphere',
        x: 340,
        y: 180,
        inputs: [
          { id: 'a', name: 'Terrain RGB', type: 'vec3' },
          { id: 'b', name: 'Night Sky', type: 'vec3' },
          { id: 'factor', name: 'Darkness', type: 'float', defaultValue: 0.5 },
        ],
        outputs: [{ id: 'out', name: 'Result', type: 'vec3' }],
      },
      {
        id: 'n_bloom_ores',
        name: 'Emissive Ore Bloom',
        category: 'effects',
        description: 'Extracts glowing torchlight and bioluminescence',
        x: 640,
        y: 180,
        inputs: [{ id: 'inColor', name: 'Color', type: 'vec3' }],
        outputs: [{ id: 'out', name: 'Glowing Scene', type: 'vec3' }],
        data: { threshold: 0.65 },
      },
      {
        id: 'master_output',
        name: 'Iris Master Output',
        category: 'output',
        description: 'Render to screen',
        x: 960,
        y: 200,
        inputs: [{ id: 'color', name: 'Final Color', type: 'vec3' }],
        outputs: [],
      },
    ],
    connections: [
      { id: 'c1', fromNodeId: 'n_albedo', fromPortId: 'rgb', toNodeId: 'n_mix_night', toPortId: 'a' },
      { id: 'c2', fromNodeId: 'n_night_tint', fromPortId: 'color', toNodeId: 'n_mix_night', toPortId: 'b' },
      { id: 'c3', fromNodeId: 'n_mix_night', fromPortId: 'out', toNodeId: 'n_bloom_ores', toPortId: 'inColor' },
      { id: 'c4', fromNodeId: 'n_bloom_ores', fromPortId: 'out', toNodeId: 'master_output', toPortId: 'color' },
    ],
  },
  {
    id: 'retro_8bit',
    title: 'Retro 8-Bit Pixelator',
    subtitle: 'Chunky screen quantizer and nostalgic arcade aesthetic',
    badge: 'Retro',
    previewColor: '#ec4899',
    description: 'Turn Minecraft into a nostalgic classic console game with crunchy pixels and subtle CRT vignette.',
    metadata: {
      name: 'Retro_8Bit_Pixelator',
      author: 'ShaderCraft Studio',
      version: '1.0.0',
      description: 'Chunky pixel resolution and CRT styling for Minecraft Iris',
      enableWavingLeaves: false,
      enableDynamicWater: false,
      enableGodRays: false,
      enableBloom: false,
      saturationBoost: 1.1,
    },
    nodes: [
      {
        id: 'n_albedo',
        name: 'Block Albedo',
        category: 'input',
        description: 'Base texture',
        x: 60,
        y: 160,
        inputs: [],
        outputs: [{ id: 'rgb', name: 'RGB', type: 'vec3' }],
      },
      {
        id: 'n_pixelate',
        name: 'Retro Pixelator',
        category: 'effects',
        description: 'Quantizes coordinates into chunky virtual retro pixels',
        x: 340,
        y: 160,
        inputs: [],
        outputs: [{ id: 'out', name: 'Pixel Color', type: 'vec3' }],
        data: { resolution: 96.0 },
      },
      {
        id: 'n_vignette',
        name: 'CRT Vignette',
        category: 'effects',
        description: 'Simulates curved glass tube shadow',
        x: 640,
        y: 160,
        inputs: [{ id: 'inColor', name: 'Color', type: 'vec3' }],
        outputs: [{ id: 'out', name: 'Color', type: 'vec3' }],
        data: { intensity: 0.45 },
      },
      {
        id: 'master_output',
        name: 'Iris Master Output',
        category: 'output',
        description: 'Render to screen',
        x: 940,
        y: 180,
        inputs: [{ id: 'color', name: 'Final Color', type: 'vec3' }],
        outputs: [],
      },
    ],
    connections: [
      { id: 'c1', fromNodeId: 'n_pixelate', fromPortId: 'out', toNodeId: 'n_vignette', toPortId: 'inColor' },
      { id: 'c2', fromNodeId: 'n_vignette', fromPortId: 'out', toNodeId: 'master_output', toPortId: 'color' },
    ],
  },
];
